version: 0.1

phases:
  build:
    commands:
      - aws deploy push --region ap-northeast-1 --application-name udemy-aws-14days-simple-bloh --s3-location s3://udemy-aws-14days-codebuild202508/sample.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
  name: sample.zip
